---
  - name: Set passwod for deploy user
    hosts: all
    become: true

    tasks:
      - name: Ensure deploy user has a password set 
        ansible.builtin.user:
          name: deploy
          password: "$6$VcLCBJ7gqiMmUD1.$Wwyl/JVlVNK3MOg1ev/z7Vcv1h9KXra5gDwKCAqXNka2oPHpGfX0MuRxF3.jd0uoYwjXvZYlyLMSrzDqu/kfX/"
      
      - name: Ensure deploy sudo requires password
        ansible.builtin.lineinfile:
          path: /etc/sudoers.d/deploy
          regexp: '^deploy'
          line: 'deploy ALL=(ALL) ALL'
          validate: 'visudo -cf %s'