---
- name: Set up self-signed certificates for HTTPS
  hosts: webserver
  become: true
  tasks:
    - name: Ensure the /etc/pki/nginx directory exists
      ansible.builtin.file:
        path: /etc/pki/nginx
        state: directory
        mode: "0755"
        owner: root

    - name: Ensure we have a /etc/pkig/nginx/private directory
      ansible.builtin.file:
        path: /etc/pki/nginx/private
        state: directory
        mode: "0700"
        owner: root

    - name: Ensure we have necessary software installed
      ansible.builtin.package:
        name: python3-cryptography
        state: present

    - name: Ensure we have a private key for our certificate
      community.crypto.openssl_privatekey:
        path: /etc/pki/nginx/private/server.key

    - name: Create a self-signed certificate
      community.crypto.x509_certificate:
        path: /etc/pki/nginx/server.crt
        privatekey_path: /etc/pki/nginx/private/server.key
        provider: selfsigned
